import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {ClerkProvider, Show, SignInButton, UserButton} from "@clerk/nextjs";
import Image from "next/image";
import { Providers } from "./providers";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"]
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"]
});

export const metadata: Metadata = {
	title: "GTrack",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ClerkProvider>
					<header className="flex min-h-dvh justify-center">
						<Show when="signed-out">
							<SignInButton mode="modal">
								<div className="flex min-h-dvh flex-col items-center justify-center gap-6">
									<Image
										src="/gtrack-logo.png"
										alt="app logo"
										width={180}
										height={180}
										loading="eager"
										className="drop-shadow-[0_16px_40px_rgba(10,132,255,0.22)]"
									/>
									<button className="apple-button px-8 py-3 text-sm font-semibold">
										Sign In
									</button>
								</div>
							</SignInButton>
						</Show>
						<Show when="signed-in">
							<div className="flex min-h-dvh w-full flex-col">
								<div className="absolute left-1/2 top-4 z-50 -translate-x-1/2 mt-1.5">
									<UserButton />
								</div>
								<Providers>
									{children}
								</Providers>
							</div>
						</Show>
					</header>
				</ClerkProvider>
			</body>
		</html>
	);
}
