import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {ClerkProvider, Show, SignInButton, SignUpButton, UserButton} from "@clerk/nextjs";
import Image from "next/image";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"]
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"]
});

export const metadata: Metadata = {
	title: "GTrack",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ClerkProvider>
					<header className="flex justify-center items-center h-screen">
						<Show when="signed-out">
							<SignInButton mode="modal">
								<div className="flex flex-col">
									<Image
										src="/gtrack-logo.png"
										alt="app logo"
										width={180}
										height={180}
										loading="eager"
									/>
									<button className="bg-app-primary border border-app-primary-border px-4 py-2 rounded-xl">
										Sign In
									</button>
								</div>
							</SignInButton>
						</Show>
						<Show when="signed-in">
							<div className="flex flex-col h-full w-full">
								<div className="self-center mt-6 z-10">
									<UserButton />
								</div>
								{children}
							</div>
						</Show>
					</header>
				</ClerkProvider>
			</body>
		</html>
	);
}
